### ISSUE TITLE
Note field

### ISSUE THREAD

**Issue by clemensp** [nulogy/richard#1]
I'd like to be able to leave quick notes, such as "brb, heating up lunch in the kitchen"

**Comment by clemensp** [comment]
I was thinking about this feature today, and I think there's more value now, now that richard-cli exists.
Basically, any script that uses richard-cli can update their status as they're going through tasks.

e.g. Our topic branch integration script can say:
"Integration script: running gorgon"
"Integration script: running gorgon:failed"
"Integration script: Integration failed.  Waiting for <Name> to resolve the problem."
etc

**Comment by arturopie** [comment]
:+1:

**Comment by ajrkerr** [comment]
Is one of the requirements to be able to update your note/status without releasing richard?

I'm wondering if it's the usecase of:
1) As a user/bot I want to set a memo when I grab richard
2) As a user/bot when I already have richard I want to set a status that others can see.

**Comment by clemensp** [comment]
Yeah, I'd like to be able to set notes without releasing richard.

Infact, if we wanted to simplify things, it'd be good enough to set notes
at any time.

---------------------------------------------------
Clemens Park
Nulogy Corporation
Email: clemensp@nulogy.com

This email is subject to the terms of Nulogy's Confidentiality policy,
which can be viewed at: http://www.nulogy.com/confidentiality/
---------------------------------------------------

**Comment by snasirca** [comment]
Copied this issue to our GitLab repo now.
