### ISSUE TITLE
Add a 'branch' field

### ISSUE THREAD

**Issue by guenia** [nulogy/richard#13]
I would like to be able to specify which branch I'm currently using. i.e: 'dev', 'release'
So that we can parallelize the usage of Richard if possible.

**Comment by arturopie** [comment]
:+1:

**Comment by ajrkerr** [comment]
This would require us to differentiate the type of queue that you're currently in... interesting.  This wouldn't be a large change and might be a good candidate for a hackday project.

**Comment by snasirca** [comment]
This would at least be helpful for deciding whether parallelization is
possible. That could then trigger off a quick chat with the other person.

Shahriyar Nasir
Nulogy Corporation
Tel: +1 416.204.0427 x405
Email: shahn@nulogy.com

**Comment by clemensp** [comment]
Now that we're only using Richard for integrating changes (gorgon cluster not affected by multiple runs), this feature may have high value.  :D

**Comment by snasirca** [comment]
Copied this to our new GitLab repo.
