### ISSUE TITLE
Remove distinction between 'get in line' and 'run gorgon'

### ISSUE THREAD

**Issue by guenia** [nulogy/richard#14]
If after waiting in line, it is now my turn to use Richard, my status should be set to running, instead of having to remember to go back and click on Run Gorgon.

**Comment by sskirby** [comment]
Is there any value in keeping the 'Run Gorgon' status if we automatically set it? How about we just remove that status altogether?

**Comment by ajrkerr** [comment]
Run Gorgon has been removed, button should now say either "Grab Richard" or "Wait in Line" to denote whether or not you're going to get it next.  The running status has been combined with the pending status.

Controller actions were simplified too, we no longer differentiate between cancelling and finishing.  They're the same thing functionally, though the UI does differentiate them as "Stop Waiting" and "Finish".

Any UI changes can be easily taken care of in the application_helper.rb if someone wants to further refine it via a pull request =)

**Comment by guenia** [comment]
Awesome!!! Thanks, Adam!
